apiVersion: v1
kind: Secret
metadata:
  name: mlops-app-secrets
  namespace: mlops-anomaly
  labels:
    app: inference-service
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"
  POSTGRES_DB: "mlops_anomaly_db"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadminpassword"
  MLFLOW_S3_ENDPOINT_URL: "http://minio.mlops-anomaly.svc.cluster.local:9000"
