apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-app-config
  namespace: mlops-anomaly
  labels:
    app: inference-service
data:
  ENVIRONMENT: "production"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_WORKERS: "2"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.mlops-anomaly.svc.cluster.local:9092"
  KAFKA_TOPIC_TELEMETRY: "industrial-sensor-telemetry"
  KAFKA_TOPIC_DLQ: "telemetry-dlq"
  MLFLOW_TRACKING_URI: "http://mlflow.mlops-anomaly.svc.cluster.local:5000"
  DRIFT_PSI_THRESHOLD_WARNING: "0.10"
  DRIFT_PSI_THRESHOLD_CRITICAL: "0.25"
