apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: mlops-anomaly
  labels:
    app: inference-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: inference-service
